language: node_js
node_js:
  - "8"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://everettz.github.io/fidelis/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/fidelis
  on:
    branch: master